In [2]:
import numpy as np

1. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули.

In [ ]:
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

2. Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

In [3]:
min = [a[np.abs(a-0.5).argmin()] for a in np.random.random((10,3))]
print(min)

[0.27951879683586645, 0.5740686653933194, 0.3241659918206301, 0.7054775140429396, 0.6088743816694302, 0.3137350538223259, 0.5761251347614635, 0.46635827618369796, 0.5664369747815194, 0.44127456226980677]


3.Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [6]:
b = np.random.random((6,6))
print(b)
c = np.asarray([np.sum(x) for x in b])
min = np.array([np.min(x) for x in b])
c/min

[[0.47923338 0.731652   0.82744243 0.82296384 0.42956302 0.18565053]
 [0.61154181 0.55837982 0.69696405 0.41586691 0.84124101 0.72609274]
 [0.17327601 0.7763538  0.22204146 0.70789285 0.41494014 0.95239965]
 [0.74009921 0.29709824 0.87871718 0.13071887 0.57849148 0.79182391]
 [0.88457804 0.80676404 0.70524926 0.37865533 0.0101976  0.41264169]
 [0.45205529 0.03152802 0.61286015 0.78881068 0.77871887 0.42696803]]


array([ 18.72607197,   9.25797719,  18.73833473,  26.13967559,
       313.6116374 ,  98.03790369])

4.На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [7]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(max(np.array([x[i] for i in range (1,9) if x[i-1] == 0])))

5


5.Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [8]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
    x[j]+=1
print (x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


6.Сколько вы можете предложить способов округлить значения в массиве до ближайшего целого?

In [12]:
y = np.array([1.3, 3.78, 4.23, 6.6, 10.5, 11, 15.54, 12.44, 14])
new_y = np.array(list(map(lambda x: round(x) , y)))
print(new_y)

[ 1  4  4  7 10 11 16 12 14]


7.Написать функцию, реализующую алгоритм k-means.

In [1]:
def index_points(points, vertex):     # индекс до ближайшего центра
    index=np.empty(len(points[:,0]))
    index=np.asarray([np.argmin(np.sum((points[i]-vertex)**2,axis=1)).astype(int) for i in range (len(points[:,0]))])
    return index
               
def new_vertex(points, vertex, index):   # новые центры из средних арифметических в кластерах
    nvertex=np.empty((len(vertex),2))
    nvertex=np.asarray ([np.mean(points[index==i], axis=0) for i in range (len(vertex))])
    return nvertex

def kmeans(points, k_or_guess):
    if type(k_or_guess)==int:
        index=np.random.choice(len(points[:,0]), k_or_guess, replace=False)
        vertex=points[index]
    else:
        vertex=k_or_guess
    x=index_points (points, vertex)
    nvertex=new_vertex (points,vertex,x)
    while (np.allclose(vertex, nvertex)==0):
        vertex=nvertex
        x=index_points (points, vertex)
        nvertex=new_vertex (points,vertex,x)
    distortion =0.0
    for i in range(len(points)):
        distortion=distortion+(np.sum((points[i]-vertex[x[i].astype(int)])**2))**0.5
    distortion=distortion/len(points[:,0])
    return vertex, distortion   